config/routes.rb
Rails.application.routes.draw do


    get '/regu', to: 'pages#regu', as: :regu
    devise_for :users
    root to: 'pages#index'
    resources :registeredapps
    namespace :api, defaults: { format: :json } do
      match '/events', to: 'events#preflight', via: [:options]
      resources :events, only: [:create]
    end
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registeredapp
  

end

app/models/registeredapp.rb
class Registeredapp < ActiveRecord::Base
    belongs_to :user
    has_many :events

  end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :registeredapps
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  before_filter :set_access_control_headers
  skip_before_action :verify_authenticity_token

    def set_access_control_headers
      headers['Access-Control-Allow-Origin'] = '*'
      headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
      headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

    def create
      registeredapp = Registeredapp.find_by(url: request.env['HTTP_ORIGIN'])
      @event = Event.new(event_params)
      @event.registeredapp = registeredapp

    if @event.save
        render json: @event, status: :created
    else
        render json: @event.errors, status: :unprocessable_entity
    end
  end

    def preflight
        head 200
    end

  private
    def event_params
      params.require(:event).permit(:name)
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up)
    devise_parameter_sanitizer.permit(:account_update)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [:regu]
end

app/controllers/registeredapps_controller.rb
class RegisteredappsController < ApplicationController

  def index

    @registeredapps = Registeredapp.all

  end

  def show
    @registeredapp = Registeredapp.find(params[:id])
    

  end

  def new
    @registeredapp = Registeredapp.new
  end

  def update

    @registeredapp = Registeredapp.find(params[:id])
    @registeredapp.name = paramas[:registeredapp][:name]
    @registeredapp.url = paramas[:registeredapp][:url]

    if @registeredapp.save
      flash[:notice] = "Registered application was saved!"
      redirect_to @registeredapp
    else
      flash.now[:alert] = "There was a problem saving the registered application"
      render :edit
    end
  end

  def create

    @registeredapp = Registeredapp.new
    @registeredapp.name = params[:registeredapp][:name]
    @registeredapp.url = params[:registeredapp][:title]

    if @registeredapp.save
      flash[:notice] = "Registered app was saved!"
      redirect_to @registeredapp
    else
      flash.now[:alert]= "There was an error saving this registered app"
      render :new
    end
  end

  def edit
    @registeredapp = registeredapp.find(params[:id])
  end

end

app/controllers/regu_controller.rb
class ReguController < ApplicationController
end

app/controllers/users_controller.rb
 class UsersController < ApplicationController
def index
  @users = User.all
end

app/helpers/application_helper.rb
module ApplicationHelper
  def header(text)
  content_for(:header) { text.to_s }
end
end

app/helpers/registered_apps_helper.rb
module RegisteredAppsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>Blocmetrics</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
    
    </div>
    <div id="navbar">
      <ul class="nav navbar-nav">
        <li><%= link_to 'Home', root_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to 'Registered APPs', regu_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav pull-right">
        <% if user_signed_in? %>
          <li class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <%= current_user.name %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to 'Profile', edit_user_registration_path %></li>
              <li><%= link_to 'Log out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log In', new_user_session_path %></li>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
  <% flash.each do |key, value| %>
    <div class="alert alert-<%= key %>">
      <%= value %>
    </div>
  <% end %>
</div>

<%= yield :top_content %>

<div class="container">
  <h1><%= yield :header %></h1>

  <%= yield %>
</div>


</div>

</body>
</html>

app/views/pages/index.html.erb
<% content_for :top_content do %>
  <div class="jumbotron">
    <div class="container">
      <h1>Welcome!</h1>
      <p>Register to get started.</p>
      <p>
        <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
        <li><%= link_to "My Apps", registeredapps_path %></li>
      </p>
    </div>
  </div>
<% end %>

app/views/pages/regu.html.erb
<h1>hello</h1>

app/views/registeredapps/index.html.erb
<h1>My Registered Applications</h1>
                <div class="row">
                  <div class="col-md-8">
                    <% @registeredapps.each do |registeredapp| %>
                      <div class="media">
                        <div class="media-body">
                          <h4 class="media-heading">
                            <%= link_to registeredapp.name, registeredapps_path %>
                          </h4>
                            <%= registeredapp.url %>
                            <%= link_to 'Show', registeredapp %>
                            <%= link_to 'Edit', edit_registeredapp_path(registeredapp) %>
                            <%= link_to 'Delete', registeredapp, method: :delete, data: { confirm: 'Are you sure?'}%>
                        </div>
                      </div>
                    <% end %>
                  </div>
                </div>
                <%= link_to "New Application", new_registeredapp_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/registeredapps/new.html.erb
<h1>New Application Registration</h1>
			<div class="row">
	<div class="col-md-8">
		<%= form_for @registeredapp do |f| %>
			<div class="form-group">
				<%= f.label :name %>
				<%= f.text_field :name, class: 'form-control', placeholder: "Website name" %>
			</div>
			<div class="form-group">
				<%= f.label :url %>
				<%= f.text_field :url, class: 'form-control', placeholder: "Web URL" %>
			</div>
			<div class="form-group">
				<%= f.submit "Save", class: 'btn btn-success' %>
			</div>
		<% end %>
	</div>
</div>

app/views/registeredapps/show.html.erb
<h1><%= link_to @registeredapp.name, @registeredapp.url %></h1>

    <%= pie_chart @registeredapp.events.group(:name).count %>
    <%= line_chart @registeredapp.events.group_by_day(:created_at).count %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>